// POST /api/summary { facts }  → an AI "coach's notes" summary of recent
// training, generated by Groq (free tier, OpenAI-compatible API).
//
// Required env var (set in Vercel; see AI_SUMMARY_SETUP.md):
//   GROQ_API_KEY
//
// Gated by the app password so the key can't be abused by anonymous callers.

import { isAuthed, unauthorized } from '../lib/auth';

export const config = { runtime: 'edge' };

const MODEL = 'llama-3.3-70b-versatile';

const SYSTEM_PROMPT = `You are an upbeat but straight-talking endurance coach reviewing an athlete's recent training data.
Write a short summary in plain prose (2-4 sentences, no markdown, no headings, no bullet points).
Reference specific numbers from the data. Call out one thing going well and, if warranted, one gentle suggestion or caution (e.g. recovery, consistency, building volume). If a race is coming up, tie the advice to it. Be encouraging and concrete, never generic.`;

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' },
  });
}

export default async function handler(req: Request): Promise<Response> {
  if (!(await isAuthed(req))) return unauthorized();
  if (req.method !== 'POST') return json({ error: 'method not allowed' }, 405);
  if (!process.env.GROQ_API_KEY) return json({ error: 'not_configured' }, 503);

  let facts = '';
  try {
    const body = (await req.json()) as { facts?: string };
    facts = (body.facts ?? '').trim();
  } catch {
    return json({ error: 'invalid body' }, 400);
  }
  if (!facts) return json({ error: 'no_data' }, 400);

  try {
    const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        authorization: `Bearer ${process.env.GROQ_API_KEY}`,
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: MODEL,
        temperature: 0.7,
        max_tokens: 240,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: facts },
        ],
      }),
    });

    if (!res.ok) {
      const detail = await res.text();
      throw new Error(`Groq error ${res.status}: ${detail.slice(0, 200)}`);
    }

    const data = await res.json();
    const text = (data.choices?.[0]?.message?.content ?? '').trim();
    if (!text) throw new Error('empty response');
    return json({ text });
  } catch (err) {
    return json({ error: err instanceof Error ? err.message : 'unknown_error' }, 502);
  }
}
